### PR TITLE
Remove MathJax rependency

### PR DESCRIPTION
**Pull request by stan6**

### CODE REVIEW

**Review by stan6 — COMMENTED** [review]
Create branch

**Comment by stan6** [comment]
Please review

**Comment by stan6** [comment]
Close the review

**Review by stan6 — COMMENTED** [review]
Approved changes

**Review by cs409-test — APPROVED** [review]
This change is fine

**Review by cs409-test — DISMISSED** [review]
Request changes

**Review by cs409-test — APPROVED** [review]
approve

**Pull request merged**
